proxy:
  http: http://127.0.0.1:7890
  https: http://127.0.0.1:7890
telegraph:
  access_token: # 第一次运行脚本自动生成，之后不可再更改，否则将失去历史文章编辑权限
  author_name: anonymous
  author_url: https://t.me/mesondzh
  short_name: mesondzh
